### PR TITLE
Update to phpBB 3.1.10

### PR DESCRIPTION
**Pull request by cabot**

### CODE REVIEW

**Comment by Galixte** [comment]
Chapeau l’artiste je voulais le faire, tu m’as devancé, merci !

**Comment by Galixte** [comment]
Hi @marc1706,

could you merge this, please ?

**Comment by CarpCharacin** [comment]
@mrgtb

**Comment by Galixte** [comment]
Hi @marc1706,

could you merge this, please ?

**Comment by marc1706** [comment]
Merged as part of #23

**Pull request closed without merging**
